# Rinna Project Configuration

# Project information
project:
  name: "Rinna"
  description: "Developer-Centric Workflow Management"
  version: "1.2.5"
  org: "heymumford"
  repo: "Rinna"

# API configuration
api:
  endpoint: "http://localhost:9080/api/v1"
  timeout:
    connection: 5000
    read: 30000
  
  # Backend services
  backend:
    java:
      host: "localhost"
      port: 8081
      health_url: "http://localhost:8081/health"

# Service management
service:
  auto_start: true
  startup_timeout: 30
  shutdown_grace: 5
  
  # Service paths (relative to project root)
  paths:
    start_script: "bin/start-services.sh"
    java_server: "bin/start-java-server.sh"
    go_server: "api/bin/start-go-server.sh"

# CLI settings
cli:
  default_type: "FEATURE"
  default_priority: "MEDIUM"
  enable_colors: true

# Environment settings
environment:
  java_version: "21"
  enable_preview: true