#!/usr/bin/env bash
# API environment setup for Rinna
# Generated by rin-setup-unified on Sun Apr  6 15:29:06 EDT 2025

# Set API environment variables
export RINNA_API_DIR="/home/emumford/NativeLinuxProjects/Rinna/api"
export PATH="$RINNA_API_DIR/bin:$PATH"
export GO111MODULE=on

# Print status
echo "Rinna API environment activated"
echo "API directory: $RINNA_API_DIR"
