name: rin-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Add concurrency control to prevent redundant workflow runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Setup and basic checks job - runs on all events
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          # Install Maven
          sudo apt-get update
          sudo apt-get install -y maven
          
          # Install Python dependencies
          if [ -f "config/python/requirements-dev.txt" ]; then
            pip install -r config/python/requirements-dev.txt
          fi
          if [ -f "python/setup.py" ]; then
            pip install -e python/
          fi

      - name: Make scripts executable
        run: |
          chmod +x bin/rinna-tests.sh
          chmod +x bin/rin
          chmod +x bin/rin-build
          chmod +x bin/python-quality 2>/dev/null || true
          chmod +x api/build.sh 2>/dev/null || true

      - name: Compile Java code
        run: cd rinna-core && mvn -B -DskipTests compile
      
      - name: Compile Go code
        run: cd api && go build ./...

  # Fast tests (unit + component) - run on every push
  fast-tests:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Run unit tests
        run: ./bin/rin-build test unit

      - name: Run component tests
        run: ./bin/rin-build test component

      - name: Basic Go tests
        run: cd api && go test ./test/simple -v

  # Integration tests - run on pull requests only
  integration-tests:
    needs: fast-tests
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Run integration tests
        run: ./bin/rin-build test integration
      
      - name: API Integration tests
        run: cd api && go test ./test/integration -v

  # Acceptance tests - run on pull requests only
  acceptance-tests:
    needs: fast-tests
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Run acceptance tests
        run: ./bin/rin-build test acceptance
        
  # Performance tests - run only on release branches
  performance-tests:
    needs: [fast-tests, integration-tests, acceptance-tests]
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Run performance tests
        run: ./bin/rin-build test performance