name: Rinna CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  rin-ci:
    name: Rinna CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Print environment info
        run: |
          echo "Java version:"
          java -version
          echo "Go version:"
          go version
          echo "Node version:"
          node --version || echo "Node not installed"
          echo "Directory structure:"
          ls -la
          
      - name: Make scripts executable
        run: |
          chmod +x bin/rinna-tests.sh
          chmod +x api/build.sh || true
          
      - name: Run CI build and test
        env:
          CI: true
        run: |
          ./bin/rinna-tests.sh
        continue-on-error: true
        
      - name: Check build outputs
        run: |
          echo "Checking build artifacts..."
          ls -la rinna-core/target/ || true
          ls -la api/ || true